### ISSUE TITLE
ImportError: No module named pylons.config

### ISSUE THREAD

**Issue by Sommerfell** [george-sattler/ckanext-piwik#1]
Hey there,

When i run the update task *paster piwik update -c /etc/ckan/default/production.ini*, I get the error:
```
File "/home/<username>/ckanext-piwik/ckanext/piwik/commands.py", line 6, in <module> import pylons.config as config
ImportError: No Module named pylons.config
```

Does anyone ever had this problem and can help me?

**Comment by george-sattler** [comment]
Hi @Sommerfell sorry, I haven't been able to do much with this extension for quite some time so not sure what the issue might be. Just a suggestion though, you could try installing a fork of this repo which has had some significant development since I last touched it: https://github.com/mateuszneumann/ckanext-piwik/network

Hope that helps!

**Comment by Sommerfell** [comment]
Hey @george-sattler,
Thank you for you fast answer. Unfortunately it didnt work.
We found another way to bring PIWIK to our CKAN without using the CKAN-Server. :+1:
